AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AwsLambdaPowertoolsPythonLayer:
      Type: AWS::Serverless::Application
      Properties:
          Location:
              ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer
              SemanticVersion: 1.26.1 # change to latest semantic version available in SAR

  MyLambdaFunction:
      Type: AWS::Serverless::Function
      Properties:
          CodeUri: src
          Handler: app.lambda_handler
          Runtime: python3.9
          Layers:
              # fetch Layer ARN from SAR App stack output
              - !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn
